github workflow: fix role name

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -21,7 +21,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         with:
-          path: juju4.ail-framework
+          path: juju4.ail_framework
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
@@ -38,19 +38,19 @@ jobs:
         run: |
           pwd
           find -ls
-          cd $GITHUB_WORKSPACE/juju4.ail-framework && yamllint .
+          cd $GITHUB_WORKSPACE/juju4.ail_framework && yamllint .
       - name: ansible-lint
         run: |
-          cd $GITHUB_WORKSPACE/juju4.ail-framework && ansible-lint
+          cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-lint
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/juju4.ail-framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
+          cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/juju4.ail-framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+          cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
       - name: On failure
         run: |
           ansible -i inventory --connection=local -m setup localhost
