github action, default-HEAD: fix wrong test suite

diff --git a/.github/workflows/default-HEAD.yml b/.github/workflows/default-HEAD.yml
--- a/.github/workflows/default-HEAD.yml
+++ b/.github/workflows/default-HEAD.yml
@@ -65,13 +65,13 @@ jobs:
           cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-lint
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS}
+          cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default-HEAD/default.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+          cd $GITHUB_WORKSPACE/juju4.ail_framework && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default-HEAD/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
       - name: On failure
         run: |
           ansible -i inventory --connection=local -m setup localhost
